fix: support renamed keyword argument for compatibility with Sentry 25.6.0+
In Sentry 25.6.0, the keyword argument `helper` was renamed to `pipeline` in `FetchUser.dispatch()`.

This led to an error `TypeError: FetchUser.dispatch() got an unexpected keyword argument 'pipeline'`
being logged and a HTTP 500 error page being shown after logging in.

see: https://github.com/getsentry/sentry/commit/56b1fdd7116f067f170013790e2d194a88e0606e